apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: unipdi-backend-local
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: MONGO_HOST
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: MONGO_DB
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):27017/$(MONGO_DB)?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
